name: Deploy Node Crud 

on: 
    push:
        branches: [main]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Code 
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: '20'
            - name: Install Dependencies
              run: npm install 
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASS}}
            - name : Build Docker Image
              run: docker build -t josemargama/node-crud .
            - name: Push Image Docker
              run: docker push josemargama/node-crud

#    deploy: 
#        needs: build
#        runs-on: self-hosted
#        steps:
#            - name : Remove Old Image
#              run : docker stop java-crud && docker rm java-crud
#            - name : Pull Image from Docker Hub
#              run: docker pull josemargama/java-crud
#            - name: Run Docker Container
#              run: docker run -d -p 8085:8085 -e DB_URL=${{secrets.DB_URL}} -e DB_USER=${{secrets.DB_USER}} -e DB_PASS='${{secrets.DB_PASS}}' --name java-crud josemargama/java-crud