name: Deploy Node Crud 

on: 
    push:
        branches: [main]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Code 
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: '20'
            - name: Install Dependencies
              run: npm install 
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASS}}
            - name : Build Docker Image
              run: docker build -t josemargama/node-crud .
            - name: Push Image Docker
              run: docker push josemargama/node-crud

    deploy: 
        needs: build
        runs-on: self-hosted
        steps:
#            - name : Remove Old Image
#              run : docker stop node-crud && docker rm node-crud
            - name : Pull Image from Docker Hub
              run: docker pull josemargama/node-crud
            - name: Run Docker Container
              run: docker run -d -p 3333:3333 -e PGHOST=${{secrets.PGHOST}} -e PGUSER=${{secrets.PGUSER}} -e PGPASSWORD='${{secrets.PGPASSWORD}} -e PGDATABASE=${{secrets.PGDATABASE}}' --name node-crud josemargama/node-crud